version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: tcgtradehub-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tcgtradehub-backend
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://admin:adminpassword@mongo:27017/tcgtradehub?authSource=admin
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: tcgtradehub-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: